### ISSUE TITLE
link na wiki

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim9#1]
Dogovorili smo se da ćete na wiki stavljati linkove na dokumente.

**Comment by kiselitza** [comment]
Pa ponuda je dostupna u .pdf-u, a intervju je doslovno rađen u MediaWiki da bi prikaz na wiki bio koliko toliko jasan.
Nisam siguran šta tačno nedostaje?

**Comment by kiselitza** [comment]
Nisam shvatio da je bilo neophodno i dokument sa wikija linkovati na wiki, mislim da je ovim riješen i issue al nek stoji otvoren dok se ne uvjerite i sami. =D

**Comment by deancupovic** [comment]
Niste linkovali ponudu na wikiju. Wiki home page bi trebao biti polazna tačka s koje je moguće doći do svih ostalih dokumenata (Pričali smo o tome na vježbama).
