### ISSUE TITLE
NFZ nisu numerisani

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim9#20]
NFZ nisu numerisani

**Comment by mklisura1** [comment]
Ja koliko vidim jesu numerisani pod stavkom 3.3 od broja 3.3.1 do 3.3.5.
![nfz](https://cloud.githubusercontent.com/assets/11391392/7378441/9c7615d4-eded-11e4-81fa-9d2e48fef32d.jpg)

**Comment by kiselitza** [comment]
Ispravili smo.
