### ISSUE TITLE
"modelirana forma"

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim9#23]
Šta znači "modelirana forma"

**Comment by kiselitza** [comment]
Mislili smo na adekvatan UI prikaz obzirom da se u prethodnim zadacima tražilo više konkretnosti, no vjerovatno je dovoljno jasno i bez "u modeliranoj formi" dijela tako da smo uklonili sporni dio

**Comment by deancupovic** [comment]
Nisam vas to pitao.
Ako mislite na "modal form" to sigurno nije "modelirana forma". Razlika je između model i modal.

**Comment by kiselitza** [comment]
Ukoliko sam dobro shvatio modal form bi predstavljala određenu vrstu pop-up prozora koji bi predstavljao taj prikaz/formu/prozor.
Ako modal form ne sadrži nikakve dodatne specifičnosti koje bi se morale ispoštovati onda bi naša forma mogla da odgovara tom formatu.

**Comment by deancupovic** [comment]
Očigledno se ne razumijemo. Hajmo iz početka:
Šta ste mislili pod "modelirana forma"?

**Comment by kiselitza** [comment]
Pod "sistem izlistava u modeliranoj formi podatke o ..." mislili smo na ekran koji se pojavi nakon zahtjeva za izvještajem (klikom na odgovarajuće dugme). Taj ekran bi se pojavio u novom prozoru i sadržavao bi izgled generisanog izvještaja koji je tražen.
