### ISSUE TITLE
Unos korisnika

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#24]
Komponenta:DodavanjeKorisnika

Commit ID: 6b368996cda563c8055639f827578247953a5ca2
Opis problema:
Dozvoljen unos korisnika iako je prikazano da je unešena pogresana šifra

Koraci za reproduciranje problema
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme dodavanje novog korisnika
4.U polje "Šifra" unijeti pasword
5.Kliknuti na dugme "Potvrdi"

Dobijeni rezultat:
Obavijest da je korisnik dodan, nakon cega se vraca na glavni meni

Ocekivani rezultat:
Onemogućavanje dodavanja korisnika dok se ne unese ispravna vrijednost za polje "Šifra
!
![greska-dodavanje-korsnika-2](https://cloud.githubusercontent.com/assets/11391445/7828162/1de9ebf6-0430-11e5-8f92-70fa79c66761.jpg)

[greska-dodavanje-korisnika](https://cloud.githubusercontent.com/assets/11391445/7828156/09379f6e-0430-11e5-843d-c581292d8561.JPG)
"

**Comment by akiselica1** [comment]
Šta znači "ispravna vrijednost za polje šifra"?

**Comment by kiselitza** [comment]
70266b9dc61ba61f4565446c87d922e622a6cd39 popravljeno
