### ISSUE TITLE
Pretraga takmicara

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#25]
Komponenta: GlavniProzor  tab-Takmičari
Commit id:6b368996cda563c8055639f827578247953a5ca2
Opis problema:
Pretraga takmicara prema "Ime i Prezime" ne vraća nikakve rezultate.
Nikakvi rezultati se ne prikazuju niti kada unesemo ime i prezime niti kada unesemo samo ime ili prezime.

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmicara"
4.Dodati novog takmicara
5.Unijeti u polje za pretragu prema imenu i prezimenu navedeno
6.Kliknuti na "Pretraži

![pretraga takmicara](https://cloud.githubusercontent.com/assets/11391445/7828367/cb22d3ee-0432-11e5-9a11-f882d1bad1aa.jpg)
![pretraga takmicara-2](https://cloud.githubusercontent.com/assets/11391445/7828368/cb27a194-0432-11e5-8255-ff552a6c7a61.jpg)

"

Dobijeni rezultat:
Nije prikazan takmicar

Očekivani rezultat:
Prikaz takmičara u tabeli ispod

**Comment by kiselitza** [comment]
Imam osjećaj da ti ništa ne dodaje ni u bazu (a ni u tabelu za pretragu) obzirom da niko iz razvojnog tima, a ni kolega koji testira @tarikdemirovic nema taj problem :+1:

**Comment by NadinHasanic** [comment]
Pretraga po imenu i prezimenu ne vraca, po kategoriji vrati 
http://pokit.org/get/img/82f6aa150624d963d866fa8229ff72bb.jpg
http://pokit.org/get/?0601322c8f88d1262cb216e4d5455056.jpg
