### ISSUE TITLE
Unos takmičara sa istim JMB-em

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#26]
Komponenta:DodavanjeTakmičara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Moguće je unijeti dva i više takmičara sa istim JMB-em

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
5.Kliknuti na dugme "Dodavanje novog takmičara"
6.U polju "Šifra" unijeti vrijednost kao kod prethodno dodanog takmičara
7.Dodati novog takmičara 

Dobijeni rezultat:
Omugućen unos dva takmičara sa istim JMB-em

Očekivani rezultat:
Poruka da se ne mogu unijeti takmičari sa istim JMB-em i onemogućavanje unosa

![unos takmicara-isti jmb](https://cloud.githubusercontent.com/assets/11391445/7828475/4070940a-0434-11e5-8cee-897f8294cd6f.jpg)

**Comment by kiselitza** [comment]
Problem nije korektno opisan jer nije moguće unijeti 2 takmičara sa istim matičnim brojem, to možeš provjeriti i u svojoj bazi podataka koju smo dostavili gdje je jasno naglašeno da je polje JMBG unique.

**Comment by NadinHasanic** [comment]
Pogledaj sliku koju sam postavio, uporedi JMB i kao sto vidis omoguceno mi je da unesem dva takmicara sa istim JMBG

**Comment by kiselitza** [comment]
#59  Ovdje je korektno opisan ovaj problem, kao što rekoh, stvarno je nemoguće unijeti dvojicu istih, poruka programa da je unos prošao nije trebala biti tu, međutim sam unos se nije desio, nikada ne unese u bazu, a samim tim ni ne ispiše u tabelu tog drugog sa istim JMBG. :/
