### ISSUE TITLE
Unos dva takmičara sa identičnim podacima

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#27]
Komponenta:DodavanjeTakmičara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Moguće je unijeti dva identična takmičara

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
5.Kliknuti na dugme "Dodavanje novog takmičara"
6.U svako polje unijeti vrijednost kao kod prethodno dodanog takmičara
7.Dodati novog takmičara

Dobijeni rezultat:
Omugućen unos dva identična takmičara

Očekivani rezultat:
Poruka da je takmičar već unesen  i onemogućavanje unosa

![unos dva identicna takmicara](https://cloud.githubusercontent.com/assets/11391445/7828529/ea45d3c8-0434-11e5-8f15-c0d117d34af0.jpg)

**Comment by kiselitza** [comment]
Slična stvar kao i sa prethodnim issue-om #26 iz potpuno istog razloga. Kako je polje JMBG označeno kao unique, to je nemoguće unijeti 2 osobe sa potpuno istim podacima. A kako sva ostala polja ne moraju biti jedinstvena (Odnosno moguće je imati 2 osobe sa istim imenom i prezimenom, rođene isti dan sa istim zvanjem i da se takmiče za isti klub) to ni ovaj issue nije korekno prijavljen.

**Comment by NadinHasanic** [comment]
Kao što sam napisao i u #26 omoguceno mi je dodat sa istim JMBG, a i sa istim podacima kao što može da vidiš na slici koju sam stavio
