### ISSUE TITLE
Nemoguće dodat novi turnir

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#28]
Komponenta:DodavanjeNovogIAzuriranjePostojecegTurnira
Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nemoguće dodati turnir jer se broj takmičara ne može promijeniti, 
a inicijalno je postavljen na 0

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Kliknuti na dugme "Dodavanje novog takmičara"
9.Dodati novog takmičara
10.Kliknuti na dugme "Dodavanje novog takmičara"
11.Dodati novog takmičara
12.Otvoriti tab Turniri
13.Kliknuti na "Dodavanje novog turnira"
14.Unijeti naziv turnira i broj dana
15.Kliknuti na "Potvrdi

Dobijeni rezultat:
Onemogućena promjena broja takmičara, time i dodavanje novog turnira

Očekivani rezultat:
Omogućena promjena broja takmičara s obzirom da smo prije toga dodali takmičare
i dodavanje novog turnira

![kreiranje turnira- uneseni takmicari](https://cloud.githubusercontent.com/assets/11391445/7828731/d94bafae-0437-11e5-9d9b-8dc184cb4a5a.jpg)
![kreiranjeturnira](https://cloud.githubusercontent.com/assets/11391445/7828730/d949e638-0437-11e5-84d4-671f5a2cb31e.jpg)

**Comment by kiselitza** [comment]
Razlog tvoje "nemogućnosti kreiranja novog turnira" nalazi se u činjenici da u tvojoj bazi nije korektno spašen bar neki od takmičara u bazi, odnosno isti ima barem neko od polja NULL, a kako svi podaci moraju biti uneseni da bi se takmičar povukao iz baze, samim tim nisi raspolagao podacima da bi mogao doći do ovog zaključka. Što se tiče broja takmičara na turniru isti se ažurira tako što se iz liste Svi takmičari klikom na ">" takmičar smjesti u listu Takmičari učesnici odnosno anologno tome u suprotnom slučaju se smanjuje.

**Comment by NadinHasanic** [comment]
Svi takmicari su uneseni sa svim podacima, spaseni su kako treba, broj bodova se ne moze unijet prilikom kreiranja takmicara i ovo nije trebalo biti oznaceno sa invalid
