### ISSUE TITLE
Dodavanje takmičara na turnir

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#29]
Komponenta:DodavanjeNovogIAzuriranjePostojecegTurnira

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
U okviru predviđenom za prikaz svih takmičara, nije prikazan nijedan takmičar, koji bi se mogao dodat na turnir

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Kliknuti na dugme "Dodavanje novog takmičara"
9.Dodati novog takmičara
10.Kliknuti na dugme "Dodavanje novog takmičara"
11.Dodati novog takmičara
12.Otvoriti tab Turniri
13.Kliknuti na "Dodavanje novog turnira"
14.Unijeti naziv turnira i broj dana
15.Kliknuti na " > " 

Dobijeni rezultat:
Nisu prikazani takmičari

Očekivani rezultat:
Prikazani takmičari, koji se mogu dodati na turnir

![kreiranjeturnira](https://cloud.githubusercontent.com/assets/11391445/7828810/ec8bfc76-0438-11e5-8545-b971f47e557b.jpg)

**Comment by kiselitza** [comment]
Objašnjeno u #28
