### ISSUE TITLE
Dodavanje kluba

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#30]
Komponenta:DodavanjeKluba

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon sto se unese pogresna vrijednost u polje "Predsjednik", kada ispravimo na odgovarajuću vrijednost ostaje greška

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Otvoriti tab Klubovi
4.Kliknuti na "Dodavanje novog kluba "
5.Unijeti odgovarajući tekst u polja "Naziv" i "Sjedište"
5.Unijeti u polje "Predsjednik" tekst "ja"
6.Kliknuti na "Potvrdi"
7.Ispraviti polje "Predsjednik" u tekst "Ja"
8.Kliknuti na "Potvrdi"
9.Ispraviti polje "Predsjednik" u tekst "Anes"
10.Kliknuti na "Potvrdi"

Dobijeni rezultat:
Greška neispravni karakteri se ne ispravlja

Očekivani rezultat:
Unos novog kluba

![unos kluba](https://cloud.githubusercontent.com/assets/11391445/7828948/835e7db6-043b-11e5-95b7-7c8a90738977.jpg)

**Comment by kiselitza** [comment]
Pogrešan ti je unos :+1: 
Obrati pažnju na validaciju polja Predsjednik .. to je polje koje mora da sadrži oboje i IME i PREZIME
dakle odgovara regexu Aaaaaa Aaaa
Obzirom da unesene vrijednosti nisu odgovarajuće samim tim se javlja poruka o neispravnom unosu

**Comment by NadinHasanic** [comment]
onda validacija pri unosu ne radi kako treba, jer mi je dopustilo da unesem dva kluba sa poljem predsjedik samo s imenom // pogledaj prva dva

**Comment by kiselitza** [comment]
Korišten je poziv iste funkcije za validaciju što bi mogao i provjeriti da si korektno naveo commit id
