### ISSUE TITLE
Izvjestaj o podacima takmičara

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#31]
Komponenta:IzvjestajOPodacimaTakmicara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Prilikom kreiranja izvještaja o podacima takmičara, nije moguće odabrati takmičara.
Combobox je prazan, također nije moguće unijeti bilo kakve vrijednosti u ostala polja na formi.

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Otvoriti tab Izvještaji
9.Kliknuti na "Izvjestaj o podacima takmičara"

Dobijeni rezultat:
Forma na kojoj nije moguć odabir takmičara niti unos bilo kakvih podataka

Očekivani rezultat:
Omogućen odabir takmičara i kreiranje izvještaja

![izvjestaj-takmicar](https://cloud.githubusercontent.com/assets/11391445/7829217/3c34bb54-043f-11e5-9141-8859997bba14.jpg)

**Comment by kiselitza** [comment]
Objašnjeno u #28

**Comment by NadinHasanic** [comment]
Procitaj i moj komentar u #28
