### ISSUE TITLE
Printanje izvjestaj o podacima takmicara

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#32]
Komponenta:IzvjestajOPodacimaTakmicara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Prilikom kreiranja izvještaja o podacima takmičara, nije moguće odabrati takmičara,
 ali klikom na "Print" otvara se forma Print sa opcijama podešavanja printanja

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Otvoriti tab Izvještaji
9.Kliknuti na "Izvjestaj o podacima takmičara"

Ako ste već dodali neke takmičare ne morate prolaziti kroz korake 3 - 7

Dobijeni rezultat:
Forma Print sa opcijama podešavanja printanja

Očekivani rezultat:
Onemogućavanje otvaranje forme Print dok se ne odabere takmičar za kojeg se pravi izvještaj

![print-izvjestaj-takmicar](https://cloud.githubusercontent.com/assets/11391445/7829314/bc67129e-0440-11e5-9ff3-89ab7b1581b2.jpg)

**Comment by kiselitza** [comment]
a98bfa964d3d9b55323e403c39a33b687c70d28d popravljeno
