### ISSUE TITLE
Izvjestaj o rang listi klubova

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#33]
Komponenta:IzvjestajORangListiklubova

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Na izvještaju o rang listi klubova broj takmičara za svaki klub je nula

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Otvoriti tab Klubovi
4.Dodati novi klub
5.Otvoriti tab Takmičari
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Kliknuti na dugme "Dodavanje novog takmičara"
9.Dodati novog takmičara
10.Otvoriti tab Izvještaji
11.Kliknuti na "Izvjestaj o rang listi klubova"

Ako ste već dodali neke takmičare i klubove ne morate prolaziti kroz korake 3 - 9

Dobijeni rezultat:
Izvjestaj sa nula takmicara za svaku klub

Očekivani rezultat:
Izvjestaj sa tačnim brojem takmičara u klubovima

![rang-lista](https://cloud.githubusercontent.com/assets/11391445/7829479/bda9382e-0442-11e5-9e31-6d92a36f5d75.jpg)

**Comment by kiselitza** [comment]
Apsolutno isti razlog naveden u #28.
Korištenje aplikacije nije bilo korektno, da si provjerio bazu i shvatio da imaš null polja te da iz tog razloga ne možeš povući nikakve podatke o takmičarima (jer tražiš konstantno nešto čega nemaš spašeno) i popunio ta polja (tj. napravio preduslove da bi izvještaj mogao biti korektan) bili bi sumirani takmičari po klubovima.
