### ISSUE TITLE
Izvjestaj o rang listi takmičara

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#34]
Komponenta:IzvjestajORangListiTakmicara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Na izvještaju o rang listi takmičara ne prikazuju se takmičari

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Otvoriti tab Izvještaji
9.Kliknuti na "Izvjestaj o rang listi takmičara"

Ako ste već dodali neke takmičare ne morate prolaziti kroz korake 3 - 7

Dobijeni rezultat:
Izvjestaj sa nula prikazanih takmičara 

Očekivani rezultat:
Izvjestaj sa prikazanim takmičarima

![rang-takmicara](https://cloud.githubusercontent.com/assets/11391445/7829562/ea447bea-0443-11e5-81cd-cbbe2acc57de.jpg)

**Comment by kiselitza** [comment]
Ponovo problem sa korisnicima i ponovo razlog koji sam naveo u #28 i još negdje nakon toga

**Comment by NadinHasanic** [comment]
Prvo ovo nisu korisnici nego takmicari, i kao sto sam naveo u #28 podaci su pravilno uneseni
