### ISSUE TITLE
Izvjestaj o rang listi klubova broj bodova

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#35]
Komponenta:IzvjestajORangListiKlubova

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Na izvještaju o rang listi klubova broj bodova za svaki klub je nula

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Otvoriti tab Klubovi
4.Dodati novi klub
5.Otvoriti tab Takmičari
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Kliknuti na dugme "Dodavanje novog takmičara"
9.Dodati novog takmičara
10.Otvoriti tab Izvještaji
11.Kliknuti na "Izvjestaj o rang listi klubova"

Ako ste već dodali neke takmičare i klubove ne morate prolaziti kroz korake 3 - 9

Dobijeni rezultat:
Izvjestaj sa nula bodova za svaku klub

Očekivani rezultat:
Izvjestaj sa tačnim brojem bodova za sve klubove

![broj-bodova](https://cloud.githubusercontent.com/assets/11391445/7829733/d3762d76-0445-11e5-8465-6f46175e1806.jpg)
![broj-bodova-nula](https://cloud.githubusercontent.com/assets/11391445/7829738/dd425776-0445-11e5-8c2f-146e0c5173a8.jpg)

**Comment by kiselitza** [comment]
fb5ffcaef8784aca69b6fe0c320a5efaea324399 popravljeno
