### ISSUE TITLE
Upravljanje rezultatima meceva-prazna forma

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#40]
Komponenta:Upravljane rezultatima mečeva

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Na formi osim naziva turnira nije prikazano nista vise 

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Otvoriti tab Turniri
4.Kliknuti na "Upravljanje rezultatima meceva"

Dobijeni rezultat:
Nije prikazano ništa(takmicari, rezultat, datum pocetka)

Očekivani rezultat:
Forma koja omogućava upravljanje rezultatima

http://pokit.org/get/?0f871b1524c5a2a2aee6ce081d5e003d.jpg

**Comment by kiselitza** [comment]
Ponovo povlačiš podatke koje ne možeš povući, sve rečeno u #28
