### ISSUE TITLE
Azuriranje postojeceg turnira

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#41]
Komponenta:Dodavanje novog i azuriranje postojeceg turnira

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Prilikom azuriranja podataka o turniru javlja grešku "Broj takmičara nije ispravan", broj se ne može promijeniti, niti dodati novi igrači ili obrisati igrači.
Zbog toga se ne može izvršiti ažuriranje 

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Otvoriti tab Turniri
4.Kliknuti na "Uređivanje"
5.Kliknuti na "Potvrdi"

Dobijeni rezultat:
Greska u broj takmičara

Očekivani rezultat:
Omogućena promjena podataka o turniru

http://pokit.org/get/img/289571a6f784a2753a6aa2c7af47a45d.jpg

**Comment by kiselitza** [comment]
Razlog greške je što si vjerovatno hardcore kroz bazu kreirao neregularan turnir, koliko vidim na slici, u tabeli na glavnoj formi stoji da je prvobitno kreirani turnir tipa Jednostruka eliminacija. Taj turnir se MORA igrati sa brojem takmičara koji je stepen broja 2. Samim tim, greška se odnosi na prvobitno uneseni turnir. A kako vidim polje "Svi takmičari" je prazno, što će reći da ono troje unesenih takmičara konkretnog turnira ne mogu biti  tipa Takmičar, ili je u pitanju određena malverzacija izvršena nad aplikacijom.

**Comment by NadinHasanic** [comment]
U bazi je promijenjen tip turnira i kroz bazu je dodan turnir jer kroz aplikaciju se nije mogao, da bi se provjerila forma azuriranja turnira
