### ISSUE TITLE
Nemogućnost printanja izvještaja o podacima takmičara

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#42]
Komponenta: Printanje izvještaja o takmičaru

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Klikom na dugme Print trebalo da se u programu OneNote otvori predpregled izvještaja koji će se printati no to se ne dešava. Nakon klika na dugme Print ne dešava se nikakva akcija.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Izvještaji
4.Kliknuti na "Izvještaj o podacima takmičara"
5.Odabrati takmičara čiji izvještaj želimo
6. Kliknuti na dugme "Print"
7. Kliknuti na dugme "Print" na prozoru "Print"

Dobijeni rezultat:
Ništa se nije desilo.

Očekivani rezultat:
Formiranje predpregleda izvještaja za printanje u Microsoft OneNote programu.

**Comment by kiselitza** [comment]
Kako je ovo dodatni feature koji nije predviđen SRS dokumentom, razvojni tim će isti uvažiti kao bug, ali ga ne planira ispravljati.
