### ISSUE TITLE
Takmičar ne može da ima 2 imena ili prezimena

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#44]
Komponenta:Dodavanje novog takmičara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Prilikom dodavanja novog takmičara nije moguće da takmičar ima 2 imena ili prezimena, što nije rijedak slučaj.

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Otvoriti tab Takmičari
4.Kliknuti na "+" za dodavanje novog takmičara
5.Unijeti 2 imena ili prezimena

Dobijeni rezultat:
Greska u unosu podataka

Očekivani rezultat:
Potvrda o dodavanju novog takmičara

![2imena](https://cloud.githubusercontent.com/assets/11389931/7845026/99fb3572-04b4-11e5-86fd-b26e54f8e06f.jpg)

![2prezimena](https://cloud.githubusercontent.com/assets/11389931/7845029/9ec5c716-04b4-11e5-92a2-a6a7efcf3189.jpg)

**Comment by kiselitza** [comment]
Istim principom moglo je biti navedeno da takmičari ne mogu imati 7 imena kao što je slučaj za latinoamerikance, razlog je jednostavan - nije praktično. Razvojni tim će ovo uvažiti kao bug ali ga ne planira ispravljati jer nigdje nije definirano da treba biti podržan taj tip formata imena
