### ISSUE TITLE
Uređivanje podataka takmičara

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#45]
Komponenta: Uređivanje podataka o takmičaru

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon uređivanja podataka o takmičaru čitava aplikacija se minimizira.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Takmičari
4.Kliknuti na "Uređivanje"
5.Kliknuti na "Potvrdi"

Dobijeni rezultat:
Čitav program se minimizira.

Očekivani rezultat:
Zatvaranje pomoćne forme za uređivanje podataka o takmičaru i ne minimiziranje glavne forme.

**Comment by kiselitza** [comment]
Volio bih vidjeti sliku problema prije nego se izjasnim, mislim da je u pitanju ista situacija kao kod kolege u #28. Dakle neko od polja u bazi je vrijednosti NULL (npr Klub, ili broj titula, ili nešto treće). Ukoliko je to u pitanju issue nije korektno prijavljen

**Comment by kiselitza** [comment]
#39
