### ISSUE TITLE
Dodavanje takmičara

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#46]
Komponenta: Dodavanje takmičara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon dodavanja takmičara čitava aplikacija se minimizira.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Takmičari
4.Kliknuti na "+" za dodavanje takmičara
5.Kliknuti na "Potvrdi"

Dobijeni rezultat:
Čitav program se minimizira.

Očekivani rezultat:
Zatvaranje pomoćne forme za dodavanje takmičara i ne minimiziranje glavne forme.

**Comment by kiselitza** [comment]
Može li neka slika da vidimo šta je u pitanju, to inače ne bi trebalo biti bug.

**Comment by adautbegovic** [comment]
Ne može slika jer se minimizira sve. Vjerovatno nije klasični bug, ali ne bi se čitava aplikacija trebala minimizirati ako se jedan pomoćni prozor zatvori.
