### ISSUE TITLE
Nemogućnost editovanja podataka o takmičaru

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#47]
Komponenta: Uređivanje podataka o takmičaru

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon uređivanja korisničkih podataka izmjene se ne prikazuju.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Takmičari
4.Kliknuti na "Uređivanje"
5. Izmijeniti klub takmičara
6.Kliknuti na "Potvrdi"

Dobijeni rezultat:
Klub takmičara se ne mijenja.

Očekivani rezultat:
Izmjena kluba takmičara.

![noviklubmiki](https://cloud.githubusercontent.com/assets/11389931/7845668/a89a4c54-04b8-11e5-84a4-323346f908c4.jpg)

![noviklubmiki1](https://cloud.githubusercontent.com/assets/11389931/7845672/ae2df4e0-04b8-11e5-96b7-b19b10db4f25.jpg)

![noviklubmiki2](https://cloud.githubusercontent.com/assets/11389931/7845677/b53d3cfa-04b8-11e5-9de0-005f506503a1.jpg)

![novklubmiki3](https://cloud.githubusercontent.com/assets/11389931/7845689/c74845fc-04b8-11e5-9394-d79ce17f3862.jpg)

**Comment by kiselitza** [comment]
b3d63be popravljeno
