### ISSUE TITLE
Manjkavost algoritama šahovskog turnira

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#48]
Komponenta: Odigravanje turnira

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon prve runde takmičenja nije moguće nastaviti takmičenje

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Turniri
4.Kliknuti na "+" za dodavanje turnira
5.Kreiranje  takmičenja jednostruko ili dvostruko eliminacionog formata
6. Unijeti rezultate prve runde

Dobijeni rezultat:
Nema daljih akcija.

Očekivani rezultat:
Pravljenje parova druge runde.

**Comment by kiselitza** [comment]
6c0beb35ae855d35d24b081b5c4e6e21987454e2 riješeno
