### ISSUE TITLE
Nemogućnost mijenjanja datuma početka meča

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#49]
Komponenta: Uređivanje podataka o meču

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon pravljenja turnira podrazumijeva se da svi mečevi počinju na prvi dan turnira i to nije moguće editovati.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Turniri
4.Kliknuti na dugme za pregled mečeva turnira
5.Kliknuti na dugme za uređivanje meča

Dobijeni rezultat:
Mogućnost unosai izmjene rezultata meča.

Očekivani rezultat:
Mogućnost unosa i izmjene rezultata meča i datuma početka meča.
![nemogucnosteditovanjadatuma](https://cloud.githubusercontent.com/assets/11389931/7846148/298a6ce2-04bc-11e5-97f8-97c093f20fba.jpg)

**Comment by kiselitza** [comment]
6c0beb35ae855d35d24b081b5c4e6e21987454e2 riješeno
