### ISSUE TITLE
Neimplementiran Swiss format takmičenja

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#50]
Komponenta: Odigravanje turnira

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon kreiranja turnira formata Swiss ne kreiraju se parovi već se samo prikaže prazna tabela takmičara.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Turniri
4.Kliknuti na "+" za dodavanje turnira
5.Kreiranje takmičenja Swiss formata
6.Kliknuti na dugme za otvaranje pregleda i uređivanja mečeva

Dobijeni rezultat:
Prazna tabela takmičara

Očekivani rezultat:
Formiranje parova prve runde takmičenja.

![swiss](https://cloud.githubusercontent.com/assets/11389931/7846423/b9342a6c-04bd-11e5-80bf-98389ff9ba09.jpg)

**Comment by kiselitza** [comment]
Bojim se da ovo nije tačno, mada na prikazanoj slici vidim nešto suprotno, molim te da provjeriš da li je u pitanju razlog dat u objašnjenju na #28. Ukoliko je bilo koje od polja za objekte koji se iz baze povlače za ovaj frame jednako NULL moraću staviti invalid tag na ovaj issue.
