### ISSUE TITLE
Izvještaj o rasporedu i satnici turnira

### ISSUE THREAD

**Issue by adautbegovic** [SoftverInzenjeringETFSA/SI2014Tim9#51]
Komponenta: Kreiranje izvještaja o rasporedu i satnici turnira

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Nakon odabiranja turnira za koji želimo izvještaj ništa se ne dešava. Također moguće je naknadno mijenjati datume počinjanja turnira koji su već kreirani. 

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Izvještaji
4.Kliknuti na "Izvještaj o rasporedu i satnici turnira"
5.Odabrati turnir

Dobijeni rezultat:
Nema daljih akcija.

Očekivani rezultat:
Izvještaj o mečevima odabranog turnira

![izvjestaj](https://cloud.githubusercontent.com/assets/11389931/7846566/a43a8bd2-04be-11e5-85fb-fc7eae17b3a1.jpg)

**Comment by ekurtanovi3** [comment]
Popravljen bug u commit ID: 89d60019dff04ea3c1a4951a59312fcef8e2760f
