### ISSUE TITLE
Izvjestaj o rang listi takmičara- print

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#52]
Komponenta:IzvjestajORangListiTakmicara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Na izvještaju o rang listi takmičara ne prikazuju se takmičari a omogućeno je printati izvještaj

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Kliknuti na dugme "Dodavanje novog takmičara"
4.Dodati novog takmičara
6.Kliknuti na dugme "Dodavanje novog takmičara"
7.Dodati novog takmičara
8.Otvoriti tab Izvještaji
9.Kliknuti na "Izvjestaj o rang listi takmičara"
10.Kliknuti na "Print"

Ako ste već dodali neke takmičare ne morate prolaziti kroz korake 3 - 7

Dobijeni rezultat:
Forma za podešavanje printanja

Očekivani rezultat:
Onemogućeno printanje izvještaja

**Comment by kiselitza** [comment]
Ponovo taj kobni #28, iako je printanje u tom trenutku bilo omogućeno i kada nema takmičara tako da će se bug uvažiti.
