### ISSUE TITLE
Printanje izvještaja o rang listi takmičara

### ISSUE THREAD

**Issue by NadinHasanic** [SoftverInzenjeringETFSA/SI2014Tim9#53]
Komponenta: Printanje izvještaja o rang listi takmičara

Commit ID:6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Klikom na dugme Print trebalo bi da se u programu OneNote otvori pregled izvještaja prije printanja

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Izvještaji
4.Kliknuti na "Izvještaj o rang listi takmičara"
5. Kliknuti na dugme "Print"
6. Kliknuti na dugme "Print" na prozoru "Print"

Dobijeni rezultat:
Ne dešava se ništa

Očekivani rezultat:
Pregled izvještaja za printanje u Microsoft OneNote programu.

**Comment by kiselitza** [comment]
Ovo nije određeno niti jednim dokumentom za razoj sistema prema tome tim će sam odlučiti da li će ovaj FEATURE privesti kraju ili ne.
