### ISSUE TITLE
Dodavanje takmičara bez kluba/broja naslova

### ISSUE THREAD

**Issue by tarikdemirovic** [SoftverInzenjeringETFSA/SI2014Tim9#54]
Modul:
Dodavanje takmičara

Commit ID:
a9f8568d4b36120e9ecfd2b70b20249862f9158e

Opis problema:
Ukoliko nema klubova u bazi, moguće je dodati takmičara bez kluba (vrijednost u koloni klub je NULL), što dovodi do bacanja izuzetka (npr u slučaju generisanja izvještaja o podacima takmičara). Broj naslova se isto tako unosi u bazu sa vrijednošću NULL.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao korisnik
3. Otvoriti tab Takmičari
4. Dodati novog takmičara (preduslov: nema klubova u bazi)
5. Otići na tab Izvještaji i kliknuti na "Izvještaj o podacima takmičara"

Dobijeni rezultat:
Unos u bazu sa vrijednošću NULL

Očekivani rezultat:
Upozorenje da je klub obavezan (ili neki drugi vid validacije).

**Comment by ElmaKusundzija** [comment]
Popravljen bug u commit ID: 40f58b275b435d8c9d541acfa8190d3beefa9559
