### ISSUE TITLE
Nemogućnost promjene korisničke šifre

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#55]
Komponenta: 
Postavke korisničkog računa

commit ID:
156d9e74da101c9ed8833c45a83f0a4500f50dc8

Opis problema:
Nakon što se otvori forma za postavke korisničkog računa koji je trenutno ulogovan u sistem, nije moguće promijeniti šifru iako je u SRS-u to navedeno kao funkcionalni zahtjev

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti formu za postavku korisničkog računa

![image](https://cloud.githubusercontent.com/assets/11525551/7897960/eac440e6-06f0-11e5-948c-4c28c7143125.png)

![image](https://cloud.githubusercontent.com/assets/11525551/7898536/5559da3a-0703-11e5-8851-39246ac40887.png)

Dobijeni rezultat:
Neispunjeno i needitabilno polj Šifra

Očekivani rezultat:
Opcija za promjenu šifre

**Comment by kiselitza** [comment]
Nijedan commit id ti nije korektan pa bih zamolio da samo to popraviš na svim issueima, svi vode na posljednji commit, međutim on nema nikakve veze ni sa jednim od issue-a jer je uticao samo na dal paket programa

**Comment by edincongo** [comment]
Ja sam stavljao id posljednjeg commita u trenutku kada sam ja tražio bugove, jer mislim da ovo služi za  provjeru da li je bug bio tu u tom trenutku. Molim te,ispravi me ako griješim.

**Comment by kiselitza** [comment]
Mislim da bi bilo korektnije da se stavi posljednji commit fajla koji sadrži bug, barem sam ja tako uradio za svoje issue. Meni lično ne smeta što nije to taj commit id, ovo ti govorim jer mislim da nisu samo moje labele pokazatelj da je nešto bug već i analiza asistenta, ali ako smatraš da je to ok uredu. :+1:  :D

**Comment by kiselitza** [comment]
60a4cdec392bc295f4baa6908a636ff9edc3b1f6 popravljeno
