### ISSUE TITLE
Dodavanje korisnika koji ima potpuno iste podatke kao već unešeni (program ispiše poruku da je korisnik uspješno dodan, ali ga ne doda u bazu)

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#56]
Komponenta: 
Dodavanje novog korisnika

commit ID:
156d9e74da101c9ed8833c45a83f0a4500f50dc8

Opis problema:
Nakon što se otvori forma za dodavanje novog korisnika, i unesu identični podaci kao kod već postojećeg korisnika, sistem izbaci poruku da je korisnik uspješno dodan, ali se u bazi ne doda novi red u tabelama korisnici i osobe.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Korisnici i formu za dodavanje novog korisnika
4. Unijeti identične podatke kao kod već postojećeg korisnika
5. Kliknuti na potvrdi

![image](https://cloud.githubusercontent.com/assets/11525551/7898019/32ee30a0-06f3-11e5-8baf-e7a2dc40d75d.png)

![image](https://cloud.githubusercontent.com/assets/11525551/7898023/4e385282-06f3-11e5-9eaf-45e4c05b020e.png)

Dobijeni rezultat:
Poruka o uspješnom dodavanju korisnika

Očekivani rezultat:
Kako program ne upisuje red u bazu u slučaju istih podataka (kako i treba), poruka da korisnik već postoji u bazi bi ovdje bila očekivani rezultat

**Comment by kiselitza** [comment]
0254b5ef55cfe19dee25f560911d6acffe59c165 popravljeno
