### ISSUE TITLE
Dodavanje korisnika iako nisu ispunjeni minimalni zahtjevi za kompleksnost šifre

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#57]
Komponenta: 
Dodavanje novog korisnika

commit ID:
156d9e7

Opis problema:
Nakon što se otvori forma za dodavanje novog korisnika, i unese šifra koja ne zadovoljava minimalne uslove kompleksnosti (6 znakova i barem 1 broj), sistem izbaci poruku da je korisnik uspješno dodan, iako je vidljiva poruka o greški da unesena šifra ne zadovoljava uslove.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Korisnici i formu za dodavanje novog korisnika
4. Unijeti šifru koja ne zadovoljava minimalne uslove kompleksnosti
5. Kliknuti na potvrdi

![image](https://cloud.githubusercontent.com/assets/11525551/7898055/4bda1e5c-06f4-11e5-8124-e89acd12190f.png)

Dobijeni rezultat:
Poruka o uspješnom dodavanju korisnika

Očekivani rezultat:
Poruka da unesena šifra ne zadovoljava potrebne uslove i povratak na formu za unos

**Comment by kiselitza** [comment]
#24
