### ISSUE TITLE
Uređivanje korisnika i nevalidan JMBG

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#58]
Komponenta: 
Uređivanje korisnika

commit ID:
156d9e7

Opis problema:
Nakon što se otvori forma za uređivanje postojećeg korisnika, i unese neki znak u polje JMBG i klikne na Potvrdi, sistem izbaci poruku da korisnik uspješno izmjenjen.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Korisnici i formu za uređivanje postojećeg korisnika
4. Unijeti JMBG koji sadrži slovo
5. Kliknuti na potvrdi

![image](https://cloud.githubusercontent.com/assets/11525551/7898107/bb34ec68-06f5-11e5-8203-d7975aa4e5a7.png)

Dobijeni rezultat:
Poruka o uspješnom uređivanju korisnika

Očekivani rezultat:
Poruka da JMBG nije validan

**Comment by kiselitza** [comment]
542298ca225973f0cafceeab58a227fbd25a12df popravljeno
