### ISSUE TITLE
Dodavanje takmičara koji ima isti JMBG kao već unešeni (program ispisuje poruku da je takmičar dodan, ali ga ne doda u bazu)

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#59]
Komponenta: 
Dodavanje novog takmičara

commit ID:
156d9e7

Opis problema:
Nakon što se otvori forma za dodavanje novog takmičara, i unese JMBG kao kod već postojećeg takmičara, sistem izbaci poruku da je korisnik uspješno dodan, ali se u bazi ne doda novi red u tabelama takmicari i osobe.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Takmicari i formu za dodavanje novog takmicara
4. Unijeti JMBG kao kod već postojećeg takmicara
5. Kliknuti na potvrdi

![image](https://cloud.githubusercontent.com/assets/11525551/7898291/baec30c6-06fb-11e5-9a5f-ab7a69c3cddd.png)

![image](https://cloud.githubusercontent.com/assets/11525551/7898295/f2d19c10-06fb-11e5-833e-2b5ff2d72e04.png)

![image](https://cloud.githubusercontent.com/assets/11525551/7898297/fc27b038-06fb-11e5-863d-f6f2366e37da.png)

Dobijeni rezultat:
Poruka o uspješnom dodavanju takmicara

Očekivani rezultat:
Kako program ne upisuje red u bazu u slučaju istog JMBG-a (kako i treba), poruka da takmicar već postoji u bazi bi ovdje bila očekivani rezultat

**Comment by kiselitza** [comment]
8e523bc197d493176d5800831db9e182a4b284d0 popravljen
