### ISSUE TITLE
Uređivanje podataka o takmičaru (program postaje unresponsive)

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#60]
Komponenta: 
Uređivanje podataka o takmičaru

Commit ID:
156d9e74da101c9ed8833c45a83f0a4500f50dc8

Opis problema:
Nakon što se pokuša otvoriti forma za uređivanje podataka o takmičaru, klikom na dugme uredi u tabeli takmičara, ne otvori se nikakva forma i čitav program postaje unresponsive (nijedna akcija ne daje bilo kakav rezultat) i jedina opcija je "ubiti" proces.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Takmičari
4.Kliknuti na "Uređivanje"

Dobijeni rezultat:
Ne desi se ništa osim toga što program postaje unresponsive.

Očekivani rezultat:
Forma za izmjenu podataka o takmičarima

**Comment by kiselitza** [comment]
#39
