### ISSUE TITLE
Dodavanje takmičara

### ISSUE THREAD

**Issue by mmujic** [SoftverInzenjeringETFSA/SI2014Tim9#61]
Komponenta: Dodavanje takmičara

Commit ID: 156d9e74da101c9ed8833c45a83f0a4500f50dc8

Opis problema: Nakon dodavanja takmičara, sistem ispisuje poruku o uspješnom dodavanju, ali takmičar nije dodan u bazu. Također, validacija JMBG je neispravna, moguće je dodati JMBG koji nije u skladu sa datumom rođenja.

Koraci za reproduciranje problema:

1.1.Pokrenuti aplikaciju
2.Prijaviti se kao korisnik
3.Otvoriti tab Takmičari
4.Kliknuti na "+" za dodavanje takmičara
5. Unijeti testne podatke (datum rođenja i početna dva broja različita)
6.Kliknuti na "Potvrdi"

![takmicar](https://cloud.githubusercontent.com/assets/11522310/7898549/a8c3af8e-0703-11e5-9b88-591f62d9e8c7.png)

Dobiveni rezultat:
Poruka o uspješnosti dodavanja takmičara.

Očekivani rezultati:
Ispis greške za nevalidan JMBG, dodavanje korisnika u bazu nakon ispravke JMBG.

**Comment by kiselitza** [comment]
popravljeno 4cdbcdf19bc8d5de563434a707131aa084847d4f
