### ISSUE TITLE
Pretraživanje takmičara

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#62]
Komponenta: 
Pretraživanje takmičara

Commit ID:
156d9e7

Opis problema:
Nakon što se otvori tab takmičari i u polju za odabir kategorije pretraživanja takmičara izabere Ime i prezime, nakon odabri afrikata (npr. č), program kao rezultat pretrage vraća sve one takmičare koji u imenu i prezimenu imaju taj afrikat bez kvacice (u ovom slučaju,vraća sve one koji imaju slovo c u imenu i prezimenu)

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Takmičari
4.U kategoriju za pretraživanje izabrati Ime i prezime
5. Kao parametar pretrage ukucati "č"
6. Kliknuti na Pretraži

![image](https://cloud.githubusercontent.com/assets/11525551/7898602/3290d7a4-0705-11e5-9bce-fc9acff7ff42.png)

Dobijeni rezultat:
Program za parametar pretrage "č" vraća sve takmičare koji imaju slovo c u imenu i prezimenu

Očekivani rezultat:
Svi takmičari koji imaju slovo č u imenu i prezimenu (program ne bi trebao vratiti ništa jer je zabranjen unos afrikata pri unosu imena i prezimena)

**Comment by kiselitza** [comment]
60a4cdec392bc295f4baa6908a636ff9edc3b1f6 isto kao i za #64
