### ISSUE TITLE
Promjena turnira

### ISSUE THREAD

**Issue by mmujic** [SoftverInzenjeringETFSA/SI2014Tim9#63]
Komponenta:Ažuriranje postojećeg turnira

Commit ID: 156d9e74da101c9ed8833c45a83f0a4500f50dc8

Opis problema:
Nije moguće mijenjati takmičare na turniru, nakon promjene formata takmičenja turnira sistem ispisuje poruku o uspješnoj izmjeni, ali turnir u stvarnosti nije izmijenjen.

Koraci za reproduciranje problema:
1.Pokrenuti aplikacija
2.Prijaviti se kao korisnik
3.Otvoriti tab Turniri
4.Kliknuti na "Uređivanje"
4. Promijeniti format takmičenja
5.Kliknuti na "Potvrdi"

![turnir1](https://cloud.githubusercontent.com/assets/11522310/7898673/9604c7a8-0707-11e5-8a40-75930e8f1326.png)
![turnir2](https://cloud.githubusercontent.com/assets/11522310/7898675/9608c2b8-0707-11e5-9885-8d8e494032b1.png)
![turnir3](https://cloud.githubusercontent.com/assets/11522310/7898674/96052fcc-0707-11e5-9a79-a134e26437f9.png)

Dobijeni rezultat:
Poruka o uspješnoj izmjeni turnira, ali bez stvarne promjene.

Očekivani rezultat:
Spremanje promjene turnira, poruka da nije moguće promijeniti učesnike na turniru.

**Comment by kiselitza** [comment]
8e6e40f6eb0bea278515f2c75b80056a6480bfb8 popravljen
