### ISSUE TITLE
Pretraživanje klubova

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#64]
Komponenta: 
Pretraživanje klubova

Commit ID:
156d9e7

Opis problema:
Nakon što se otvori tab klubovi i u polju za odabir kategorije pretraživanja klubova izabere Naziv, nakon odabira afrikata (npr. č), program kao rezultat pretrage vraća sve one klubove koji u nazivu imaju taj afrikat bez kvacice (u ovom slučaju,vraća sve one koji imaju slovo c u nazivu)

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Klubovi
4.U kategoriju za pretraživanje izabrati Naziv
5. Kao parametar pretrage ukucati "č"
6. Kliknuti na Pretraži

![image](https://cloud.githubusercontent.com/assets/11525551/7898693/3bb5b5f4-0708-11e5-8037-6407073db142.png)

Dobijeni rezultat:
Program za parametar pretrage "č" vraća sve klubove koji imaju slovo c u nazivu

Očekivani rezultat:
Svi klubovi koji imaju slovo č u nazivu (program ne bi trebao vratiti ništa jer je zabranjen unos afrikata pri unosu naziva)

**Comment by kiselitza** [comment]
60a4cdec392bc295f4baa6908a636ff9edc3b1f6 ispravljeno, biće i novi database encoding
