### ISSUE TITLE
Izvještaj o podacima takmičara (ostala polja se ne mijenjaju nakon promjene drop down polja Izaberite takmicara)

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#74]
Komponenta: 
Izvještaj o podacima takmičara

commit ID:
156d9e7

Opis problema:
Nakon što se promijeni vrijednost na drop-down polju Izaberite takmicara nakon prethodnog odabira takmicara (na formi Izvještaj o podacima takmicara), ne promijene se vrijednosti ostalih polja na formi.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Izvještaji
4.Izabrati Izvještaj o podacima takmičara
5. Na drop-down polju Izaberite takmičara izabrati nekog takmičara
6. Ponoviti korak 5.

![image](https://cloud.githubusercontent.com/assets/11525551/7899382/e0dc0674-0720-11e5-9095-93cecc1eee96.png)

Dobijeni rezultat:
Nakon ponovnog odabira takmicara na drop-downu Izaberite takmicara, ne azuriraju se ostala polja

Očekivani rezultat:
Azurirana sva polja nakon svakog odabira takmicara

**Comment by kiselitza** [comment]
Paša moj to je jer su ti klubovi null, to je do tebe, nije bug :D

**Comment by edincongo** [comment]
Paša, pa bez obzira što je prazno to polje, valjda bi se ostala trebala ažurirati kako treba :D

**Comment by edincongo** [comment]
A evo sad vidim da je klub obavezno polje. Do mene,izvinjavam se. Ali je onda bug sto je moguce dodati takmicara a da nije unesen klub.:D
