### ISSUE TITLE
Dodavanje novog takmičara bez kluba

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#75]
Komponenta: 
Dodavanje novog takmičara

commit ID:
156d9e7

Opis problema:
Moguće je uspješno dodati novog takmičara bez da je izabran klub (slučaj da je u trenutku dodavanja novog takmicara tabela klubovi prazna), što stvara neke druge probleme.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Takmicari
4.Kliknuti na button za kreiranje novog takmicara (potrebno je da tabela klubova bude prazna)
5. Popuniti podatke i kliknuti na button Potvrdi

Dobijeni rezultat:
Uspješno kreiran takmicar bez obzira sto nije izabran klub

Očekivani rezultat:
Poruka da se ne može kreirati takmicar jer nije izabran klub

**Comment by kiselitza** [comment]
#54
