### ISSUE TITLE
Izvještaj rezultata za jedan takmičarski dan

### ISSUE THREAD

**Issue by edincongo** [SoftverInzenjeringETFSA/SI2014Tim9#76]
Komponenta: 
Izvještaj rezultata za jedan takmičarski dan

commit ID:
156d9e7

Opis problema:
Na formi izvještaja rezultata za jedan takmičarski dan, nakon odabira turnira i datuma, ne prikazuju se vezani rezultati.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Prijaviti se
3.Otvoriti tab Izvještaji
4.Izabrati Izvještaj rezultata za jedan takmičarski dan
5. Na drop-down polju Turnir izaberite neki turnir i izaberite datum

![image](https://cloud.githubusercontent.com/assets/11525551/7899491/f7ba0554-0724-11e5-982f-2a4de22c49cd.png)

![image](https://cloud.githubusercontent.com/assets/11525551/7899498/2ce835f2-0725-11e5-89ce-7fedca5df5e6.png)

Dobijeni rezultat:
Nakon odabira turnira i datuma na formi za izvještaj rezultata za jedan takmičarski dan, ne prikazuju se vezani rezultati.

Očekivani rezultat:
Prikaz vezanih rezultata nakon odabira turnira i datuma.

**Comment by ElmaKusundzija** [comment]
Popravljen bug u commit ID: 0a4b62d8104d604304bcecb9fd5c9fe411a61164
